export enum IconChooser {
  MONEY = 0,
  REMOVE = 1,
  CHECK = 2,
  CHEVRON = 3,
  EDIT = 4,
  MENU = 5,
  CHECK_NO_BACKGROUND = 6,
  SEARCH = 7,
  INCREASE_PLUS = 8,
  DECREASE_MINUS = 9,
  SHOPPING_CART = 10,
  FOOD = 11,
  CALENDAR = 12,
}
