const ADD_BILL_FORM = {
  PRODUCT: "PRODUCT",
  PRICE: "PRICE",
  USER: "USER",
  EXPENSE_TYPE: "EXPENSE_TYPE",
  ID: "ID",
};

const PRODUCT_FORM = {
  NAME: "NAME",
  AMOUNT: "AMOUNT",
  DATE: "DATE",
};

export { ADD_BILL_FORM, PRODUCT_FORM };
