export const SCREEN_NAME = {
  USER_SCREEN: "USER_SCREEN",
  EXPENSE_SCREEN: "EXPENSE_SCREEN",
  PAYMENT_SCREEN: "PAYMENT_SCREEN",
  SETTING_SCREEN: "SETTING_SCREEN",
  ROOT_SCREEN: "ROOT_SCREEN",
  INVENTORY_SCREEN: "INVENTORY_SCREEN",
};
