export const SCREEN_NAME = {
  USER_SCREEN: "USER_SCREEN",
  EXPENSE_SCREEN: "EXPENSE_SCREEN",
  PAYMENT_SCREEN: "PAYMENT_SCREEN",
  SETTING_SCREEN: "SETTING_SCREEN",
  ROOT_SCREEN: "ROOT_SCREEN",
  INVENTORY_SCREEN: "INVENTORY_SCREEN",
  EDIT_SCANNER_SCREEN: "EDIT_SCANNER_SCREEN",
  SCANNER_SCREEN: "SCANNER_SCREEN",
};

export enum Screen {
  USER_SCREEN = 0,
  EXPENSE_SCREEN = 1,
  PAYMENT_SCREEN = 2,
  SETTING_SCREEN = 3,
  ROOT_SCREEN = 4,
  INVENTORY_SCREEN = 5,
  EDIT_SCANNER_SCREEN = 6,
  SCANNER_SCREEN = 7,
}
